GET https://cse341node-samson.herokuapp.com/contacts/62a55e772437910123fc88ee

GET https://cse341node-samson.herokuapp.com/contacts/62a55e772437910123fc88ef

GET https://cse341node-samson.herokuapp.com/contacts/62a55e772437910123fc88f0

GET https://cse341node-samson.herokuapp.com/contacts